% List of files to be compiled
%
% A simple string entry indicates that are no dependencies.
%
% If a entry of type `cell` (nested list) is found, the first string represents
% the __main__ file, and the others represent dependencies to be compiled
% together with the __main__ file.

COMPILE_LIST = { ...
  'version.c', ...
  'ctx_new.c', ...
  'ctx_term.c', ...
  'ctx_shutdown.c', ...
  'ctx_get.c', ...
  'ctx_set.c', ...
  'socket.c', ...
  {'close.c'     , 'util/conversions.c', 'util/socket.c' , 'util/errors.c'} ...
  {'bind.c'      , 'util/conversions.c', 'util/socket.c' , 'util/errors.c'} ...
  {'unbind.c'    , 'util/conversions.c', 'util/socket.c' , 'util/errors.c'} ...
  {'connect.c'   , 'util/conversions.c', 'util/socket.c' , 'util/errors.c'} ...
  {'disconnect.c', 'util/conversions.c', 'util/socket.c' , 'util/errors.c'} ...
  {'getsockopt.c', 'util/conversions.c', 'util/sockopt.c', 'util/socket.c', 'util/errors.c'} ...
  {'setsockopt.c', 'util/conversions.c', 'util/sockopt.c', 'util/socket.c', 'util/errors.c'} ...
  {'send.c'      , 'util/conversions.c', 'util/socket.c' , 'util/errors.c'} ...
  {'recv.c'      , 'util/conversions.c', 'util/socket.c' , 'util/errors.c'} ...
};
