% make.m
%
% Builds core mex API.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% ZMQ CONFIGURATION:
ZMQ_INCLUDE_PATH = '/usr/local/Cellar/zeromq/4.0.4/include/';
ZMQ_LIB_PATH = '/usr/local/Cellar/zeromq/4.0.4/lib/';
ZMQ_COMPILE_FLAGS = sprintf('-I%s -L%s', ZMQ_INCLUDE_PATH, ZMQ_LIB_PATH);

%% CORE API FILE LIST
CORE_FILE_LIST = { ...
                'src/core/zmq_version.c', ...
                'src/core/zmq_ctx_new.c', ...
                'src/core/zmq_ctx_term.c', ...
                'src/core/zmq_ctx_shutdown.c', ...
                'src/core/zmq_ctx_get.c', ...
                'src/core/zmq_ctx_set.c', ...
                'src/core/zmq_socket.c' ...
                };
        

%% BUILD
BUILD_FUNCTION = @(file) eval(['mex -largeArrayDims -O ', ZMQ_COMPILE_FLAGS, sprintf(' %s ', char(file)), '-lzmq -outdir lib']);
cellfun(BUILD_FUNCTION, CORE_FILE_LIST);